### ISSUE TITLE
Universum 1.0.0 plan

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#240]
- [x] Move contents of current Readme to 'Getting started' section of documentation #232
- [x] Add proper Readme for Github with links to Read the Docs #237
- [x] Remove contents of current Readme from index page and replace with actual minimal landing page #143 
- [x] Community docs #234
- [x] Create logo #238
- [x] Policies configuration
     * Pull request policy (squash)
     * Commit policy (only to master, only via pull request)
     * Web hooks

**Comment by k-dovgan** [comment]
All done
